# /etc/zsh/zlogout: system-wide .zlogout file for zsh(1).

# Copyright © 1998—2016 Sam Hocevar <sam@hocevar.net>
# This file is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# to Public License, Version 2, as published by the WTFPL Task Force.
# See http://www.wtfpl.net/ for more details.

