# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

# 0.2 by Sam Hocevar - 7 Jan 1999
# 0.3 by Sam Hocevar - 26 Feb 2011

# Enhanced path
if true #[[ -z "$PATH" || "$PATH" == "/bin:/usr/bin" ]]
then
    PATH="/usr/bin:/usr/sbin:/bin:/usr/games:/usr/local/bin"
    PATH="$PATH:/sbin:/usr/local/sbin:/opt/gnu/bin:/usr/lib/cgi-bin"
    PATH="$PATH:$HOME/bin"
    export PATH
fi

# Different prompts for root and normal users
PS1="%# "

# Store system information
UNAME=`uname`

# Disable auto log off timeout
TMOUT=

