# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

# Copyright © 1999—2016 Sam Hocevar <sam@hocevar.net>
# This file is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# to Public License, Version 2, as published by the WTFPL Task Force.
# See http://www.wtfpl.net/ for more details.

# Enhanced path
PATH="/usr/bin:/usr/sbin:/bin:/usr/games:/usr/local/bin"
PATH="$PATH:/sbin:/usr/local/sbin:/opt/gnu/bin:/usr/lib/cgi-bin"
PATH="$PATH:$HOME/bin"
export PATH

# Different prompts for root and normal users
PS1="%# "

# Store system information
UNAME=`uname`

# Disable auto log off timeout
TMOUT=

